name: build

on:
  workflow_dispatch:

env:
  TAG_NAME: latest

jobs:
  buildroot:
    name: Firmware
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # - { "platform": "gk7205v210", "release": "lite" }
          - { "platform": "gk7205v210", "release": "ultimate" }
          # - { "platform": "gk7205v210", "release": "fpv" }
          # - { "platform": "gk7205v210", "release": "rubyfpv" }
          # - { "platform": "gk7205v210", "release": "venc" }
          # - { "platform": "gk7205v300", "release": "lite" }
          # - { "platform": "gk7205v300", "release": "ultimate" }
          # - { "platform": "gk7205v300", "release": "fpv" }
          # - { "platform": "gk7205v300", "release": "lte" }
          # - { "platform": "gk7205v300", "release": "rubyfpv" }
          # - { "platform": "gk7205v300", "release": "venc" }

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Prepare firmware
        run: |
          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
          echo CACHE_DATE=$(date +%m) >> ${GITHUB_ENV}

      - name: Install GCC 13
        run: |
          sudo apt update
          sudo apt install gcc-13 g++-13
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100
          gcc --version

      - name: Setup ccache
        uses: actions/cache@v4
        with:
          path: /tmp/ccache
          key: ${{ matrix.platform }}_${{ matrix.release }}-${{ env.CACHE_DATE }}

      - name: Restore ccache
        uses: actions/cache/restore@v4
        with:
          path: /tmp/ccache
          key: ${{ matrix.platform }}_${{ matrix.release }}-${{ env.CACHE_DATE }}

      - name: Build firmware
        run: |
          export GIT_HASH=$(git rev-parse --short ${GITHUB_SHA})
          export GIT_BRANCH=${GITHUB_REF_NAME}
          echo GIT_HASH=${GIT_HASH} >> ${GITHUB_ENV}
          echo GIT_BRANCH=${GIT_BRANCH} >> ${GITHUB_ENV}

          mkdir -p /tmp/ccache
          ln -s /tmp/ccache ${HOME}/.ccache
          make BOARD=${{ matrix.platform }}_${{ matrix.release }}

          TIME=$(date -d @${SECONDS} +%M:%S)
          echo TIME=${TIME} >> ${GITHUB_ENV}

          NORFW=${GITHUB_WORKSPACE}/output/images/openipc.${{ matrix.platform }}-nor-${{ matrix.release }}.tgz
          if [ -e ${NORFW} ]; then
            echo NORFW=${NORFW} >> ${GITHUB_ENV}
          fi

          NANDFW=${GITHUB_WORKSPACE}/output/images/openipc.${{ matrix.platform }}-nand-${{ matrix.release }}.tgz
          if [ -e ${NANDFW} ]; then
            echo NANDFW=${NANDFW} >> ${GITHUB_ENV}
          fi

      - name: Upload firmware
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: |
            ${{ env.NORFW }}
            ${{ env.NANDFW }}
